chore: to add horizontal constraint to collapsible panel
commercetools/ui-kit pull request #1703
Opened 2020-11-30 19:14 UTC by YahiaElTai

#### Summary

## Description

2020-11-30 20:22 UTC, YahiaElTai commented
I have updated percy snapshots, only one new prop added.

2020-12-01 09:57 UTC, jonnybel commented on packages/components/collapsible-panel/src/collapsible-panel.styles.js
> +  min-width: 284px;
I suppose this is intended to be the value of the smallest supported constraint

```suggestion
  min-width: ${vars.constraint6};
```

2020-12-01 10:24 UTC, jonnybel commented on .changeset/chilled-chairs-ring.md
> +"@commercetools-uikit/collapsible-panel": patch
I think we should consider these `feat`, since we're adding a new prop to the component 🙂

2020-12-01 11:24 UTC, jonnybel approved these changes
Looks good! Thanks :)

2020-12-03 09:07 UTC, emmenko requested changes
We should provide at least a couple of VRTs for the constraint sizes.

2020-12-03 09:07 UTC, emmenko commented on packages/components/collapsible-panel/package.json
> +    "@commercetools-uikit/constraints": "10.42.2",
Nit: can you sort the dep alphabetically?

2020-12-03 09:07 UTC, emmenko commented on packages/components/collapsible-panel/src/collapsible-panel.js
> +    'xl',
I would leave them out, as this is a new prop and we don't need to be backwards compatible.

2020-12-03 09:07 UTC, emmenko commented on packages/components/collapsible-panel/src/collapsible-panel.styles.js
> +  min-width: ${vars.constraint6};
🎉

2020-12-03 13:10 UTC, emmenko commented
The VRTs show some weird behavior:

<img width="701" alt="Screenshot 2020-12-03 at 14 09 09" src="https://user-images.githubusercontent.com/1110551/101022109-39aabf00-3571-11eb-832b-3f14ec8939ee.png">

@YahiaElTai please don't approve the VRTs by yourself. One of the reviewer should do that. Thanks.

2020-12-03 13:12 UTC, YahiaElTai commented
> The VRTs show some weird behavior:
> 
> <img alt="Screenshot 2020-12-03 at 14 09 09" width="701" src="https://user-images.githubusercontent.com/1110551/101022109-39aabf00-3571-11eb-832b-3f14ec8939ee.png">
> 
> @YahiaElTai please don't approve the VRTs by yourself. One of the reviewer should do that. Thanks.

Ah so these snapshots are to be approved by the reviewers not me, sorry xD should have asked for help. I will take a look Thanks for the details

2020-12-03 17:05 UTC, emmenko reviewed
Thanks for the fix!

2020-12-03 17:05 UTC, emmenko commented on packages/components/collapsible-panel/src/collapsible-panel.js
> +          )}
```suggestion
          max={props.horizontalConstraint}
```

The `parseHorizontalConstraintProp` is only used for backwards compatibility. We can simply require the new prop now as-is.

2020-12-03 17:15 UTC, emmenko approved these changes
Thanks! 🎉

2020-12-03 17:18 UTC, jonnybel commented
The VRTs seemed to be good now 👍 The diffs are only due to the new prop and added specs.

2020-12-04 07:51 UTC, merged

2020-12-04 07:51 UTC, emmenko commented
Let's go! Thanks again 👌