Migrate localized-multiline-text-input to typescript
commercetools/ui-kit pull request #2096
Opened 2022-02-09 18:37 UTC by ddouglasz

Migrate localized-multiline-text-input to typescript

2022-02-10 09:32 UTC, CarlosCortizasCT commented on packages/components/inputs/localized-multiline-text-input/src/translation-input.styles.ts
> +type TTranslateInputStylesProps = {
Could we use the name based on this filename? 
I was expecting it to be `TTranslationInputStylesProps`

2022-02-10 11:14 UTC, CarlosCortizasCT commented on packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.tsx
> +                  language as string
I'm wondering why we need to explicitly say `language` is a string when here we're iterating over the `languages` constants which has been actually defined as an array of strings.

2022-02-10 16:38 UTC, emmenko reviewed
Looks good overall, just some minor improvements.

2022-02-10 16:38 UTC, emmenko commented on packages/components/inputs/localized-multiline-text-input/docs/usage-example.tsx
> +export default Example;
This file is expected to be a `.js` file

2022-02-10 16:38 UTC, emmenko commented on packages/components/inputs/localized-multiline-text-input/src/translation-input.tsx
> +    if (props.isCollapsed) onToggle && onToggle();
```suggestion
    if (props.isCollapsed) onToggle?.();
```

2022-02-15 08:41 UTC, CarlosCortizasCT requested changes

2022-02-15 08:41 UTC, CarlosCortizasCT commented on packages/components/inputs/localized-multiline-text-input/src/translation-input.tsx
> +  ChangeEventHandler,
```suggestion
  type ChangeEventHandler,
```

2022-02-15 11:31 UTC, CarlosCortizasCT approved these changes
LGTM

2022-02-21 20:02 UTC, emmenko approved these changes

2022-02-21 20:05 UTC, merged