refactor(select-field): migrate select field package to typescript
commercetools/ui-kit pull request #2108
Opened 2022-02-14 09:12 UTC by ddouglasz

Migrate `select-field package` component to typescript

2022-02-14 10:24 UTC, CarlosCortizasCT requested changes

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +import { Component, isValidElement, ReactElement, type ReactNode } from 'react';
```suggestion
import { 
  Component, 
  isValidElement, 
  type ReactElement, 
  type ReactNode,
} from 'react';
```

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +  onChange?: () => void;
I'm missing the event type in the function declaration.
Also, we should remove the "Signature" comment in the description as it's going to be automatically generated.

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +  onFocus?: () => void;
I'm missing the event type in the function declaration.
Also, we should remove the "Signature" comment in the description as it's going to be automatically generated.

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +  onInputChange?: () => void;
I'm missing the `newValue` and `actionMeta` types in the function declaration.
Also, we should remove the "Signature" comment in the description as it's going to be automatically generated.

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +  // options?: OptionsOrGroups<unknown, GroupBase<unknown>> | boolean;
We have two types here if we count the commented one.
Should we remove the comment to avoid confusion?

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +   * Sets the tabIndex attribute on the input
For `react-select` props maybe we could include a link to its props docs as we've done in other or our components ([example](https://github.com/commercetools/ui-kit/blob/main/packages/components/inputs/async-select-input/src/async-select-input.tsx#L92))

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +  inputValue?: ReactSelectProps['inputValue'];
I'm missing the description for this `inputValue` prop.
Could you add it?

2022-02-14 10:24 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +   * 	Icon to display on the left of the placeholder text and selected value. Has no effect when isMulti is enabled.
```suggestion
   * Icon to display on the left of the placeholder text and selected value. Has no effect when isMulti is enabled.
```

2022-02-15 07:59 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +   */
```suggestion
   * <br />
   * [Props from React select was used](https://react-select.com/props)
   */
```

2022-02-15 12:08 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +  showOptionGroupDivider?: boolean;
This `showOptionGroupDivider` does not have any JSDoc. Could we add it?

2022-02-16 12:40 UTC, kark commented on packages/components/fields/select-field/src/select-field.tsx
> +declare type TOptionObject = {
Nit: I'm wondering if we need the `declare` syntax here. Same applies to line 28

2022-02-16 13:55 UTC, kark commented on packages/components/fields/select-field/src/select-field.tsx
> +  components?: {
Hey @ddouglasz I thought I 'll leave a couple more pesky nitpicks 😅
```suggestion
* * <br/>
   * [Props from React select was used](https://react-select.com/props)
   */
  components?: ReactSelectProps['components'];
```

2022-02-16 13:55 UTC, kark commented on packages/components/fields/select-field/src/select-field.tsx
> +  onInfoButtonClick?: () => void;
```suggestion
  onInfoButtonClick?: (
    event: MouseEvent<HTMLButtonElement> | KeyboardEvent<HTMLButtonElement>
  ) => void;
```

2022-02-16 13:55 UTC, kark commented on packages/components/fields/select-field/src/select-field.tsx
> +  onBlur?: () => void;
```suggestion
  onBlur?: (event: TEvent) => void;
```

2022-02-16 16:34 UTC, CarlosCortizasCT requested changes

2022-02-16 16:34 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +   * Dom element to portal the select menu to
```suggestion
   * Dom element to portal the select menu to
   * <br/>
   * [Props from React select was used](https://react-select.com/props)
```

2022-02-16 16:34 UTC, CarlosCortizasCT commented on packages/components/fields/select-field/src/select-field.tsx
> +  description?: string | ReactNode;
```suggestion
  description?: ReactNode;
```

2022-02-17 14:04 UTC, CarlosCortizasCT approved these changes
LGTM

2022-02-18 11:32 UTC, Rhotimee approved these changes

2022-02-18 11:41 UTC, merged